// Automatically generated constants for Typst
#let pm = $plus.minus$
#let פמ = $plus.minus$

#let פרמטר_קושי_A = $1.59692 pm 0.00027$
#let cauchy_a = פרמטר_קושי_A
#let פרמטר_קושי_A_ערך = $1.59692 pm 0.00027$
#let cauchy_a_val = פרמטר_קושי_A_ערך
#let שגיאת_פרמטר_קושי_A = $0.00027$
#let cauchy_a_err = שגיאת_פרמטר_קושי_A
#let שגיאת_פרמטר_קושי_A_ערך = $0.00027$
#let cauchy_a_err_val = שגיאת_פרמטר_קושי_A_ערך
#let פרמטר_קושי_B = $8394.9 pm 72.0 "nm"^2$
#let cauchy_b = פרמטר_קושי_B
#let פרמטר_קושי_B_ערך = $8394.9 pm 72.0$
#let cauchy_b_val = פרמטר_קושי_B_ערך
#let שגיאת_פרמטר_קושי_B = $72.0 "nm"^2$
#let cauchy_b_err = שגיאת_פרמטר_קושי_B
#let שגיאת_פרמטר_קושי_B_ערך = $72.0$
#let cauchy_b_err_val = שגיאת_פרמטר_קושי_B_ערך
#let קבוע_רידברג_מנסרה = $(1.1120 pm 0.0043) times 10^(7) "m"^(-1)$
#let rydberg_prism = קבוע_רידברג_מנסרה
#let קבוע_רידברג_מנסרה_ערך = $(1.1120 pm 0.0043) times 10^(7)$
#let rydberg_prism_val = קבוע_רידברג_מנסרה_ערך
#let שגיאת_קבוע_רידברג_מנסרה = $4.2689 times 10^(4) "m"^(-1)$
#let rydberg_prism_err = שגיאת_קבוע_רידברג_מנסרה
#let שגיאת_קבוע_רידברג_מנסרה_ערך = $4.2689 times 10^(4)$
#let rydberg_prism_err_val = שגיאת_קבוע_רידברג_מנסרה_ערך
#let קבוע_רידברג_סריג = $(1.0911 pm 0.0019) times 10^(7) "m"^(-1)$
#let rydberg_grating = קבוע_רידברג_סריג
#let קבוע_רידברג_סריג_ערך = $(1.0911 pm 0.0019) times 10^(7)$
#let rydberg_grating_val = קבוע_רידברג_סריג_ערך
#let שגיאת_קבוע_רידברג_סריג = $1.8901 times 10^(4) "m"^(-1)$
#let rydberg_grating_err = שגיאת_קבוע_רידברג_סריג
#let שגיאת_קבוע_רידברג_סריג_ערך = $1.8901 times 10^(4)$
#let rydberg_grating_err_val = שגיאת_קבוע_רידברג_סריג_ערך
#let מרחק_רידברג_מנסרה = $3.43$
#let rydberg_prism_sigma = מרחק_רידברג_מנסרה
#let מרחק_רידברג_מנסרה_ערך = $3.43$
#let rydberg_prism_sigma_val = מרחק_רידברג_מנסרה_ערך
#let שגיאת_מרחק_רידברג_מנסרה = none
#let rydberg_prism_sigma_err = שגיאת_מרחק_רידברג_מנסרה
#let שגיאת_מרחק_רידברג_מנסרה_ערך = none
#let rydberg_prism_sigma_err_val = שגיאת_מרחק_רידברג_מנסרה_ערך
#let מרחק_רידברג_סריג = $3.32$
#let rydberg_grating_sigma = מרחק_רידברג_סריג
#let מרחק_רידברג_סריג_ערך = $3.32$
#let rydberg_grating_sigma_val = מרחק_רידברג_סריג_ערך
#let שגיאת_מרחק_רידברג_סריג = none
#let rydberg_grating_sigma_err = שגיאת_מרחק_רידברג_סריג
#let שגיאת_מרחק_רידברג_סריג_ערך = none
#let rydberg_grating_sigma_err_val = שגיאת_מרחק_רידברג_סריג_ערך
#let מרחק_כספית = $0.02$
#let mercury_green_sigma = מרחק_כספית
#let מרחק_כספית_ערך = $0.02$
#let mercury_green_sigma_val = מרחק_כספית_ערך
#let שגיאת_מרחק_כספית = none
#let mercury_green_sigma_err = שגיאת_מרחק_כספית
#let שגיאת_מרחק_כספית_ערך = none
#let mercury_green_sigma_err_val = שגיאת_מרחק_כספית_ערך
