[project]
name = "studies"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.2.0",
    "matplotlib>=3.10.8",
    "numpy>=2.4.4",
    "ruff>=0.15.14",
    "scipy>=1.17.1",
    "scipy-stubs~=1.17.1",
]

[dependency-groups]
dev = [
    "ruff>=0.15.12",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["physlab"]

[tool.ruff]
extend-exclude = [
    ".virtual_documents",
    "2025S",
    "2025W",
    "2026W",
]

[tool.ruff.lint]
extend-select = [
    "I", # isort (import sorting)
    "UP", # pyupgrade (modernize syntax)
    "B", # flake8-bugbear (catch common bugs)
    "SIM", # flake8-simplify (simplify code logic)
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F403"]
"*.ipynb" = ["E402"]
