// Automatically generated constants for Typst
#let pm = $plus.minus$
#let פמ = $plus.minus$

#let k_theo = $5499.46 "m"^(-1)$
#let k_theo = k_theo
#let k_theo_ערך = $5499.46$
#let k_theo_val = k_theo_ערך
#let שגיאת_k_theo = none
#let k_theo_err = שגיאת_k_theo
#let שגיאת_k_theo_ערך = none
#let k_theo_err_val = שגיאת_k_theo_ערך
#let I_res_m1 = $0.4682 pm 0.0237 "A"$
#let I_res_m1 = I_res_m1
#let I_res_m1_ערך = $0.4682 pm 0.0237$
#let I_res_m1_val = I_res_m1_ערך
#let שגיאת_I_res_m1 = $0.0237 "A"$
#let I_res_m1_err = שגיאת_I_res_m1
#let שגיאת_I_res_m1_ערך = $0.0237$
#let I_res_m1_err_val = שגיאת_I_res_m1_ערך
#let k_m1 = $6061.0 pm 307.2 "m"^(-1)$
#let k_m1 = k_m1
#let k_m1_ערך = $6061.0 pm 307.2$
#let k_m1_val = k_m1_ערך
#let שגיאת_k_m1 = $307.2 "m"^(-1)$
#let k_m1_err = שגיאת_k_m1
#let שגיאת_k_m1_ערך = $307.2$
#let k_m1_err_val = שגיאת_k_m1_ערך
#let I_res_m3 = $0.4577 pm 0.0231 "A"$
#let I_res_m3 = I_res_m3
#let I_res_m3_ערך = $0.4577 pm 0.0231$
#let I_res_m3_val = I_res_m3_ערך
#let שגיאת_I_res_m3 = $0.0231 "A"$
#let I_res_m3_err = שגיאת_I_res_m3
#let שגיאת_I_res_m3_ערך = $0.0231$
#let I_res_m3_err_val = שגיאת_I_res_m3_ערך
#let k_m3 = $6199.3 pm 313.2 "m"^(-1)$
#let k_m3 = k_m3
#let k_m3_ערך = $6199.3 pm 313.2$
#let k_m3_val = k_m3_ערך
#let שגיאת_k_m3 = $313.2 "m"^(-1)$
#let k_m3_err = שגיאת_k_m3
#let שגיאת_k_m3_ערך = $313.2$
#let k_m3_err_val = שגיאת_k_m3_ערך
#let I_res_fit = $0.4661 pm 0.0001 "A"$
#let I_res_fit = I_res_fit
#let I_res_fit_ערך = $0.4661 pm 0.0001$
#let I_res_fit_val = I_res_fit_ערך
#let שגיאת_I_res_fit = $0.0001 "A"$
#let I_res_fit_err = שגיאת_I_res_fit
#let שגיאת_I_res_fit_ערך = $0.0001$
#let I_res_fit_err_val = שגיאת_I_res_fit_ערך
#let w_fit = $0.02308 pm 0.00021 "A"$
#let w_fit = w_fit
#let w_fit_ערך = $0.02308 pm 0.00021$
#let w_fit_val = w_fit_ערך
#let שגיאת_w_fit = $0.00021 "A"$
#let w_fit_err = שגיאת_w_fit
#let שגיאת_w_fit_ערך = $0.00021$
#let w_fit_err_val = שגיאת_w_fit_ערך
#let dI_FWHM = $0.0462 pm 0.0004 "A"$
#let dI_FWHM = dI_FWHM
#let dI_FWHM_ערך = $0.0462 pm 0.0004$
#let dI_FWHM_val = dI_FWHM_ערך
#let שגיאת_dI_FWHM = $0.0004 "A"$
#let dI_FWHM_err = שגיאת_dI_FWHM
#let שגיאת_dI_FWHM_ערך = $0.0004$
#let dI_FWHM_err_val = שגיאת_dI_FWHM_ערך
#let dB_FWHM = $0.360 pm 0.018 "mT"$
#let dB_FWHM = dB_FWHM
#let dB_FWHM_ערך = $0.360 pm 0.018$
#let dB_FWHM_val = dB_FWHM_ערך
#let שגיאת_dB_FWHM = $0.018 "mT"$
#let dB_FWHM_err = שגיאת_dB_FWHM
#let שגיאת_dB_FWHM_ערך = $0.018$
#let dB_FWHM_err_val = שגיאת_dB_FWHM_ערך
#let domega = $(6.34 pm 0.33) times 10^(7) "rad" / "sec"$
#let domega = domega
#let domega_ערך = $(6.34 pm 0.33) times 10^(7)$
#let domega_val = domega_ערך
#let שגיאת_domega = $3.25 times 10^(6) "rad" / "sec"$
#let domega_err = שגיאת_domega
#let שגיאת_domega_ערך = $3.25 times 10^(6)$
#let domega_err_val = שגיאת_domega_ערך
#let T2 = $31.57 pm 1.62 "ns"$
#let T2 = T2
#let T2_ערך = $31.57 pm 1.62$
#let T2_val = T2_ערך
#let שגיאת_T2 = $1.62 "ns"$
#let T2_err = שגיאת_T2
#let שגיאת_T2_ערך = $1.62$
#let T2_err_val = שגיאת_T2_ערך
#let g_DPPH = $2.0036 pm 0.0002$
#let g_DPPH = g_DPPH
#let g_DPPH_ערך = $2.0036 pm 0.0002$
#let g_DPPH_val = g_DPPH_ערך
#let שגיאת_g_DPPH = $0.0002$
#let g_DPPH_err = שגיאת_g_DPPH
#let שגיאת_g_DPPH_ערך = $0.0002$
#let g_DPPH_err_val = שגיאת_g_DPPH_ערך
#let nu_RF = $100.0 pm 0.1 "MHz"$
#let nu_RF = nu_RF
#let nu_RF_ערך = $100.0 pm 0.1$
#let nu_RF_val = nu_RF_ערך
#let שגיאת_nu_RF = $0.1 "MHz"$
#let nu_RF_err = שגיאת_nu_RF
#let שגיאת_nu_RF_ערך = $0.1$
#let nu_RF_err_val = שגיאת_nu_RF_ערך
#let h_const = $6.626 times 10^(-34) "J" dot "sec"$
#let h_const = h_const
#let h_const_ערך = $6.626 times 10^(-34)$
#let h_const_val = h_const_ערך
#let שגיאת_h_const = none
#let h_const_err = שגיאת_h_const
#let שגיאת_h_const_ערך = none
#let h_const_err_val = שגיאת_h_const_ערך
#let mu_B_const = $9.274 times 10^(-24) "J/T"$
#let mu_B_const = mu_B_const
#let mu_B_const_ערך = $9.274 times 10^(-24)$
#let mu_B_const_val = mu_B_const_ערך
#let שגיאת_mu_B_const = none
#let mu_B_const_err = שגיאת_mu_B_const
#let שגיאת_mu_B_const_ערך = none
#let mu_B_const_err_val = שגיאת_mu_B_const_ערך
#let mu_0_const = $1.257 times 10^(-6) "N/A"^2$
#let mu_0_const = mu_0_const
#let mu_0_const_ערך = $1.257 times 10^(-6)$
#let mu_0_const_val = mu_0_const_ערך
#let שגיאת_mu_0_const = none
#let mu_0_const_err = שגיאת_mu_0_const
#let שגיאת_mu_0_const_ערך = none
#let mu_0_const_err_val = שגיאת_mu_0_const_ערך
#let N_turns = $440$
#let N_turns = N_turns
#let N_turns_ערך = $440$
#let N_turns_val = N_turns_ערך
#let שגיאת_N_turns = none
#let N_turns_err = שגיאת_N_turns
#let שגיאת_N_turns_ערך = none
#let N_turns_err_val = שגיאת_N_turns_ערך
#let h_coil = $0.069 "m"$
#let h_coil = h_coil
#let h_coil_ערך = $0.069$
#let h_coil_val = h_coil_ערך
#let שגיאת_h_coil = none
#let h_coil_err = שגיאת_h_coil
#let שגיאת_h_coil_ערך = none
#let h_coil_err_val = שגיאת_h_coil_ערך
#let D_avg = $0.0405 "m"$
#let D_avg = D_avg
#let D_avg_ערך = $0.0405$
#let D_avg_val = D_avg_ערך
#let שגיאת_D_avg = none
#let D_avg_err = שגיאת_D_avg
#let שגיאת_D_avg_ערך = none
#let D_avg_err_val = שגיאת_D_avg_ערך
#let dev_m1 = $10.2 "%"$
#let dev_m1 = dev_m1
#let dev_m1_ערך = $10.2$
#let dev_m1_val = dev_m1_ערך
#let שגיאת_dev_m1 = none
#let dev_m1_err = שגיאת_dev_m1
#let שגיאת_dev_m1_ערך = none
#let dev_m1_err_val = שגיאת_dev_m1_ערך
#let dev_m3 = $12.7 "%"$
#let dev_m3 = dev_m3
#let dev_m3_ערך = $12.7$
#let dev_m3_val = dev_m3_ערך
#let שגיאת_dev_m3 = none
#let dev_m3_err = שגיאת_dev_m3
#let שגיאת_dev_m3_ערך = none
#let dev_m3_err_val = שגיאת_dev_m3_ערך
#let sig_dist_m1 = $1.8$
#let sig_dist_m1 = sig_dist_m1
#let sig_dist_m1_ערך = $1.8$
#let sig_dist_m1_val = sig_dist_m1_ערך
#let שגיאת_sig_dist_m1 = none
#let sig_dist_m1_err = שגיאת_sig_dist_m1
#let שגיאת_sig_dist_m1_ערך = none
#let sig_dist_m1_err_val = שגיאת_sig_dist_m1_ערך
#let sig_dist_m3 = $2.2$
#let sig_dist_m3 = sig_dist_m3
#let sig_dist_m3_ערך = $2.2$
#let sig_dist_m3_val = sig_dist_m3_ערך
#let שגיאת_sig_dist_m3 = none
#let sig_dist_m3_err = שגיאת_sig_dist_m3
#let שגיאת_sig_dist_m3_ערך = none
#let sig_dist_m3_err_val = שגיאת_sig_dist_m3_ערך
