// Automatically generated constants for Typst
#let pm = $plus.minus$
#let פמ = $plus.minus$

#let התנגדות_סליל_ראשי = $11.80 pm 0.01 Omega$
#let primary_coil_resistance = התנגדות_סליל_ראשי
#let התנגדות_סליל_ראשי_ערך = $11.80 pm 0.01$
#let primary_coil_resistance_val = התנגדות_סליל_ראשי_ערך
#let שגיאת_התנגדות_סליל_ראשי = $0.01 Omega$
#let primary_coil_resistance_err = שגיאת_התנגדות_סליל_ראשי
#let שגיאת_התנגדות_סליל_ראשי_ערך = $0.01$
#let primary_coil_resistance_err_val = שגיאת_התנגדות_סליל_ראשי_ערך
#let השראות_סליל_ראשי = $(5.70 pm 0.37) dot 10^(-3) "H"$
#let primary_coil_inductance = השראות_סליל_ראשי
#let השראות_סליל_ראשי_ערך = $(5.70 pm 0.37) dot 10^(-3)$
#let primary_coil_inductance_val = השראות_סליל_ראשי_ערך
#let שגיאת_השראות_סליל_ראשי = $0.37 dot 10^(-3) "H"$
#let primary_coil_inductance_err = שגיאת_השראות_סליל_ראשי
#let שגיאת_השראות_סליל_ראשי_ערך = $0.37 dot 10^(-3)$
#let primary_coil_inductance_err_val = שגיאת_השראות_סליל_ראשי_ערך
#let התנגדות_סליל_משני = $123.30 pm 0.14 Omega$
#let secondary_coil_resistance = התנגדות_סליל_משני
#let התנגדות_סליל_משני_ערך = $123.30 pm 0.14$
#let secondary_coil_resistance_val = התנגדות_סליל_משני_ערך
#let שגיאת_התנגדות_סליל_משני = $0.14 Omega$
#let secondary_coil_resistance_err = שגיאת_התנגדות_סליל_משני
#let שגיאת_התנגדות_סליל_משני_ערך = $0.14$
#let secondary_coil_resistance_err_val = שגיאת_התנגדות_סליל_משני_ערך
#let השראות_סליל_משני = $(84.10 pm 4.52) dot 10^(-3) "H"$
#let secondary_coil_inductance = השראות_סליל_משני
#let השראות_סליל_משני_ערך = $(84.10 pm 4.52) dot 10^(-3)$
#let secondary_coil_inductance_val = השראות_סליל_משני_ערך
#let שגיאת_השראות_סליל_משני = $4.52 dot 10^(-3) "H"$
#let secondary_coil_inductance_err = שגיאת_השראות_סליל_משני
#let שגיאת_השראות_סליל_משני_ערך = $4.52 dot 10^(-3)$
#let secondary_coil_inductance_err_val = שגיאת_השראות_סליל_משני_ערך
#let זרם_בסליל_הראשי = $0.0162 "A"$
#let primary_coil_current = זרם_בסליל_הראשי
#let זרם_בסליל_הראשי_ערך = $0.0162$
#let primary_coil_current_val = זרם_בסליל_הראשי_ערך
#let שגיאת_זרם_בסליל_הראשי = none
#let primary_coil_current_err = שגיאת_זרם_בסליל_הראשי
#let שגיאת_זרם_בסליל_הראשי_ערך = none
#let primary_coil_current_err_val = שגיאת_זרם_בסליל_הראשי_ערך
#let שדה_מגנטי_במרכז_הסליל = $3.39 dot 10^(-5) "T"$
#let central_magnetic_field = שדה_מגנטי_במרכז_הסליל
#let שדה_מגנטי_במרכז_הסליל_ערך = $3.39 dot 10^(-5)$
#let central_magnetic_field_val = שדה_מגנטי_במרכז_הסליל_ערך
#let שגיאת_שדה_מגנטי_במרכז_הסליל = none
#let central_magnetic_field_err = שגיאת_שדה_מגנטי_במרכז_הסליל
#let שגיאת_שדה_מגנטי_במרכז_הסליל_ערך = none
#let central_magnetic_field_err_val = שגיאת_שדה_מגנטי_במרכז_הסליל_ערך
#let יחס_השנאה_אידיאלי = $0.653$
#let ideal_transformation_ratio = יחס_השנאה_אידיאלי
#let יחס_השנאה_אידיאלי_ערך = $0.653$
#let ideal_transformation_ratio_val = יחס_השנאה_אידיאלי_ערך
#let שגיאת_יחס_השנאה_אידיאלי = none
#let ideal_transformation_ratio_err = שגיאת_יחס_השנאה_אידיאלי
#let שגיאת_יחס_השנאה_אידיאלי_ערך = none
#let ideal_transformation_ratio_err_val = שגיאת_יחס_השנאה_אידיאלי_ערך
#let התנגדות_חוט_החימום = $81.79 Omega$
#let oven_heater_resistance = התנגדות_חוט_החימום
#let התנגדות_חוט_החימום_ערך = $81.79$
#let oven_heater_resistance_val = התנגדות_חוט_החימום_ערך
#let שגיאת_התנגדות_חוט_החימום = none
#let oven_heater_resistance_err = שגיאת_התנגדות_חוט_החימום
#let שגיאת_התנגדות_חוט_החימום_ערך = none
#let oven_heater_resistance_err_val = שגיאת_התנגדות_חוט_החימום_ערך
#let הספק_התנור = $19.56 "W"$
#let oven_heater_power = הספק_התנור
#let הספק_התנור_ערך = $19.56$
#let oven_heater_power_val = הספק_התנור_ערך
#let שגיאת_הספק_התנור = none
#let oven_heater_power_err = שגיאת_הספק_התנור
#let שגיאת_הספק_התנור_ערך = none
#let oven_heater_power_err_val = שגיאת_הספק_התנור_ערך
#let קצב_חימום_אידיאלי = $19.17 "K" / "sec"$
#let ideal_heating_rate = קצב_חימום_אידיאלי
#let קצב_חימום_אידיאלי_ערך = $19.17$
#let ideal_heating_rate_val = קצב_חימום_אידיאלי_ערך
#let שגיאת_קצב_חימום_אידיאלי = none
#let ideal_heating_rate_err = שגיאת_קצב_חימום_אידיאלי
#let שגיאת_קצב_חימום_אידיאלי_ערך = none
#let ideal_heating_rate_err_val = שגיאת_קצב_חימום_אידיאלי_ערך
#let התנגדות_תרמית_של_הגליל = $1.119 "K" / "W"$
#let thermal_resistance = התנגדות_תרמית_של_הגליל
#let התנגדות_תרמית_של_הגליל_ערך = $1.119$
#let thermal_resistance_val = התנגדות_תרמית_של_הגליל_ערך
#let שגיאת_התנגדות_תרמית_של_הגליל = none
#let thermal_resistance_err = שגיאת_התנגדות_תרמית_של_הגליל
#let שגיאת_התנגדות_תרמית_של_הגליל_ערך = none
#let thermal_resistance_err_val = שגיאת_התנגדות_תרמית_של_הגליל_ערך
#let זמן_התקררות_ל_350_קלווין = $3.22 "sec"$
#let cooling_time_to_350k = זמן_התקררות_ל_350_קלווין
#let זמן_התקררות_ל_350_קלווין_ערך = $3.22$
#let cooling_time_to_350k_val = זמן_התקררות_ל_350_קלווין_ערך
#let שגיאת_זמן_התקררות_ל_350_קלווין = none
#let cooling_time_to_350k_err = שגיאת_זמן_התקררות_ל_350_קלווין
#let שגיאת_זמן_התקררות_ל_350_קלווין_ערך = none
#let cooling_time_to_350k_err_val = שגיאת_זמן_התקררות_ל_350_קלווין_ערך
