// Automatically generated constants for Typst
#let pm = $plus.minus$
#let פמ = $plus.minus$

#let התנגדות_סליל_ראשוני = $11.80 pm 0.01 Omega$
#let primary_coil_resistance = התנגדות_סליל_ראשוני
#let שגיאת_התנגדות_סליל_ראשוני = $0.01 Omega$
#let primary_coil_resistance_err = שגיאת_התנגדות_סליל_ראשוני
#let השראות_סליל_ראשוני = $(5.70 pm 0.37) dot 10^(-3) "H"$
#let primary_coil_inductance = השראות_סליל_ראשוני
#let שגיאת_השראות_סליל_ראשוני = $0.37 dot 10^(-3) "H"$
#let primary_coil_inductance_err = שגיאת_השראות_סליל_ראשוני
#let התנגדות_סליל_משני = $123.30 pm 0.14 Omega$
#let secondary_coil_resistance = התנגדות_סליל_משני
#let שגיאת_התנגדות_סליל_משני = $0.14 Omega$
#let secondary_coil_resistance_err = שגיאת_התנגדות_סליל_משני
#let השראות_סליל_משני = $(84.10 pm 4.52) dot 10^(-3) "H"$
#let secondary_coil_inductance = השראות_סליל_משני
#let שגיאת_השראות_סליל_משני = $4.52 dot 10^(-3) "H"$
#let secondary_coil_inductance_err = שגיאת_השראות_סליל_משני
#let זרם_בסליל_הראשוני = $0.0162 "A"$
#let primary_coil_current = זרם_בסליל_הראשוני
#let שגיאת_זרם_בסליל_הראשוני = none
#let primary_coil_current_err = שגיאת_זרם_בסליל_הראשוני
#let שדה_מגנטי_במרכז_הסליל = $3.39 dot 10^(-5) "T"$
#let central_magnetic_field = שדה_מגנטי_במרכז_הסליל
#let שגיאת_שדה_מגנטי_במרכז_הסליל = none
#let central_magnetic_field_err = שגיאת_שדה_מגנטי_במרכז_הסליל
#let יחס_השנאה_אידיאלי = $0.653$
#let ideal_transformation_ratio = יחס_השנאה_אידיאלי
#let שגיאת_יחס_השנאה_אידיאלי = none
#let ideal_transformation_ratio_err = שגיאת_יחס_השנאה_אידיאלי
#let התנגדות_חוט_החימום = $81.79 Omega$
#let oven_heater_resistance = התנגדות_חוט_החימום
#let שגיאת_התנגדות_חוט_החימום = none
#let oven_heater_resistance_err = שגיאת_התנגדות_חוט_החימום
#let הספק_התנור = $19.56 "W"$
#let oven_heater_power = הספק_התנור
#let שגיאת_הספק_התנור = none
#let oven_heater_power_err = שגיאת_הספק_התנור
#let קצב_חימום_אידיאלי = $19.17 "K" / "sec"$
#let ideal_heating_rate = קצב_חימום_אידיאלי
#let שגיאת_קצב_חימום_אידיאלי = none
#let ideal_heating_rate_err = שגיאת_קצב_חימום_אידיאלי
#let התנגדות_תרמית_של_הגליל = $1.119 "K" / "W"$
#let thermal_resistance = התנגדות_תרמית_של_הגליל
#let שגיאת_התנגדות_תרמית_של_הגליל = none
#let thermal_resistance_err = שגיאת_התנגדות_תרמית_של_הגליל
#let זמן_התקררות_ל_350_קלווין = $3.22 "sec"$
#let cooling_time_to_350k = זמן_התקררות_ל_350_קלווין
#let שגיאת_זמן_התקררות_ל_350_קלווין = none
#let cooling_time_to_350k_err = שגיאת_זמן_התקררות_ל_350_קלווין
