// Automatically generated constants for Typst
#let pm = $plus.minus$
#let פמ = $plus.minus$

#let התנגדות_סליל_ראשוני = $11.80 Omega$
#let primary_coil_resistance = $11.80 Omega$
#let שגיאת_התנגדות_סליל_ראשוני = none
#let primary_coil_resistance_err = none
#let השראות_סליל_ראשוני = $5.70 dot 10^(-3) "H"$
#let primary_coil_inductance = $5.70 dot 10^(-3) "H"$
#let שגיאת_השראות_סליל_ראשוני = none
#let primary_coil_inductance_err = none
#let התנגדות_סליל_משני = $123.30 Omega$
#let secondary_coil_resistance = $123.30 Omega$
#let שגיאת_התנגדות_סליל_משני = none
#let secondary_coil_resistance_err = none
#let השראות_סליל_משני = $(84.10 pm 3.50) dot 10^(-3) "H"$
#let secondary_coil_inductance = $(84.10 pm 3.50) dot 10^(-3) "H"$
#let שגיאת_השראות_סליל_משני = $3.50 dot 10^(-3) "H"$
#let secondary_coil_inductance_err = $3.50 dot 10^(-3) "H"$
#let זרם_בסליל_הראשוני = $0.0162 "A"$
#let primary_coil_current = $0.0162 "A"$
#let שגיאת_זרם_בסליל_הראשוני = none
#let primary_coil_current_err = none
#let שדה_מגנטי_במרכז_הסליל = $3.39 dot 10^(-5) "T"$
#let central_magnetic_field = $3.39 dot 10^(-5) "T"$
#let שגיאת_שדה_מגנטי_במרכז_הסליל = none
#let central_magnetic_field_err = none
#let יחס_השנאה_אידיאלי = $0.653$
#let ideal_transformation_ratio = $0.653$
#let שגיאת_יחס_השנאה_אידיאלי = none
#let ideal_transformation_ratio_err = none
#let התנגדות_חוט_החימום = $81.79 Omega$
#let oven_heater_resistance = $81.79 Omega$
#let שגיאת_התנגדות_חוט_החימום = none
#let oven_heater_resistance_err = none
#let הספק_התנור = $19.56 "W"$
#let oven_heater_power = $19.56 "W"$
#let שגיאת_הספק_התנור = none
#let oven_heater_power_err = none
#let קצב_חימום_אידיאלי = $19.17 "K" / "sec"$
#let ideal_heating_rate = $19.17 "K" / "sec"$
#let שגיאת_קצב_חימום_אידיאלי = none
#let ideal_heating_rate_err = none
#let התנגדות_תרמית_של_הגליל = $1.119 "K" / "W"$
#let thermal_resistance = $1.119 "K" / "W"$
#let שגיאת_התנגדות_תרמית_של_הגליל = none
#let thermal_resistance_err = none
#let זמן_התקררות_ל_350_קלווין = $3.22 "sec"$
#let cooling_time_to_350k = $3.22 "sec"$
#let שגיאת_זמן_התקררות_ל_350_קלווין = none
#let cooling_time_to_350k_err = none
